apiVersion: v1
kind: Service
metadata:
  name: bank-leumi-app-service
spec:
  type: NodePort
  ports:
    - port: 443      # External port
      targetPort: 5000  # port in the pod
      nodePort: 32443  # port for node access
  selector:
    app: bank-leumi-app

