apiVersion: v1
kind: Service
metadata:
  name: bank-leumi-app-service
spec:
  type: ClusterIP
  ports:
    - port: 5000          # Port the Service will expose
      targetPort: 5000   # Port inside the pod
  selector:
    app: bank-leumi-app

